version: '3.8'
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: food-calculator
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

